# Bind: localhost:8082 # default listen address
# Set global ssh defaults
DefaultSSHKey: ~/.ssh/id_rsa
DefaultUsername: anon
IdleTimeout: 120s # close idle connections after 120sec. 0 to disable
# ProxyFallback: true # act as a regular proxy for anything that is not found in the endpoint list
Endpoints:
  # Imagine a service running on ingres.public.com that binds to 127.0.0.1:80
  # Expose service on ingres.public.com:80 as http://test.network.local/
  - VHostname: test.network.local
    SSHHostname: ingres.public.com
    # SSHPort: 22 # default
    # SSHConnectTimeout: 15s # default
    # SSHKey: # defaults to .DefaultSSHKey
    # Username: # defaults to .DefaultUsername
    # ProxyAddress: localhost:80 # default
  # jumpbox.public.com is a public server that is connected to a private network
  # Here you expose other.network.local:9200 as if it was directly publicly reachable
  - VHostname: other.network.local:9200
    SSHHostname: jumpbox.public.com
    ProxyAddress: other.network.local:9200
# Enable more verbose output
Debug: true